theme: jekyll-theme-minimal
photo: https://media.licdn.com/dms/image/v2/C4D03AQGjW-VU-wNBrA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1575657004087?e=1793232000&v=beta&t=eNLJfI3Au9eCjaVpX5Omgu97-vP-HLH1jfVdRQC0Rmg
title: Andrey Espinhel | Portfolio
description: IT student at NBCC | Systems Analysis, Business Intelligence, Agile, Software Development Student
