theme: jekyll-theme-minimal
logo: https://media.licdn.com/dms/image/v2/C4D03AQGjW-VU-wNBrA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1575657004087?e=1793232000&v=beta&t=eNLJfI3Au9eCjaVpX5Omgu97-vP-HLH1jfVdRQC0Rmg
title: Andrey Espinhel 
description: "I am an IT student at NBCC in the Information Technology: Software Development program, with experience in systems analysis, business intelligence, and Agile product ownership. I enjoy solving problems with data and automation and my goal is to build a career in IT infrastructure, networking, or data."
